stat_enseignant_homepage:
    pattern:  /accueil
    defaults: { _controller: StatEnseignantBundle:Cours:index }

stat_enseignant_details:
    pattern:  /details/{id}/{type}
    defaults: { _controller: StatEnseignantBundle:Cours:details }

stat_enseignant_details_actif:
    pattern:  /details/actif/{id}/{type}
    defaults: { _controller: StatEnseignantBundle:Cours:detailsActif }

stat_enseignant_etudiant_global:
    pattern:  /etudiants/{id}
    defaults: { _controller: StatEnseignantBundle:Cours:global }

stat_enseignant_etudiant_detail:
    pattern:  /etudiants/detail/{cours}/{name}
    defaults: { _controller: StatEnseignantBundle:Cours:detailsEtudiant, name: 1, cours: 1 }